version: '3'

services:

  arkumida-webapi:
    image: arkumida-webapi:latest
    container_name: arkumida-webapi
    restart: always

    ports:
        - 127.0.0.1:5220:8080

    networks:
      - arkumida-net

networks:
  arkumida-net:
    driver: bridge
    external: true


