version: '3'

services:

  # PostgreSQL
  arkumida-postgresql:
    image: arkumida-infrastructure-postgres
    container_name: arkumida-postgresql
    restart: always

    ports:
      - 127.0.0.1:5433:5432 # Do not need it in Prod

    environment:
      POSTGRES_PASSWORD: ju3iyNYcWvfv7Rx3ZCv50FFBwaAU4V

    volumes:
      - arkumida_postgresql_data:/var/lib/postgresql/data

    networks:
      - arkumida-net

  # Adminer
  arkumida-adminer:
    image: adminer
    container_name: arkumida-adminer
    restart: always

    ports:
      - 127.0.0.1:9082:8080

    networks:
      - arkumida-net

  # Opensearch
  arkumida-opensearch:
    image: opensearchproject/opensearch:latest
    container_name: arkumida-opensearch
    restart: always

    ports:
      - 127.0.0.1:9200:9200 # Do not need it in Prod

    environment:
      - cluster.name=arkumida-cluster
      - node.name=arkumida0
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536

    volumes:
      - arkumida_opensearch_data:/usr/share/opensearch/data

    networks:
      - arkumida-net

volumes:

  # Arkumida postgresql database storage
  arkumida_postgresql_data:

  # Arkumida OpenSearch storage
  arkumida_opensearch_data:

networks:
  arkumida-net:
    driver: bridge
